name = "lemodpack for the client"
author = "thefirethirteen"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3104258be149661f056b10acb2d1620ab4df07ecb01b6cfff38096dd72536c56"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.1", "1.19.2"]
